#!/usr/bin/env bash
# This script does the following tasks!:
# Creates a file /var/run/myscript.pid
# Displays to infinity and beyond indefinitely!
# Displays `I hate the kill` command whenever it receives a SIGTERM signal!
# Displays `Y U no love me?!` whenever it receives a SIGINT signal!
# Deletes the file /var/run/myscript.pid
# Terminates itself when:
## It receives a SIGQUIT !
## It receives a SIGTERM signal !

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/holbertonscript.pid; exit" SIGQUIT

while true
do
    echo 'To infinity and beyond'
    sleep 2
done
