#!/usr/bin/env bash
# This script displays 'To infinity and beyond' when:
# In between each iteration of the loop

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
