#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu
# ssh ubuntu@192.168.157.122 -i ~/.ssh/school

ssh -i ~/.ssh/school -o StrictHostKeyChecking=no ubuntu@$1
